Sql server
MeltanoLabs/evidence-ext pull request #37
Opened 2023-05-20 00:12 UTC by matsonj

2023-05-20 00:14 UTC, matsonj commented
the meltano.yml has a bunch of changes bc the meltano parser changed the spacing. sorry about that.

2023-05-20 03:05 UTC, edgarrmondragon requested changes
Thanks @matsonj! I've left some comments based on the implementation I see on the Evidence codebase.

2023-05-20 03:05 UTC, edgarrmondragon commented on meltano.yml
> +      env: MSSQL_CERTIFICATE
Evidence seems to expect these settings to be nested inside an `options` object:

```suggestion
    - name: settings.mssql.options.trust_server_certificate
      env: MSSQL_TRUST_SERVER_CERTIFICATE
```

https://github.com/evidence-dev/evidence/blob/main/packages/mssql/index.cjs#L101-L105

2023-05-20 03:05 UTC, edgarrmondragon commented on meltano.yml
> +      env: MSSQL_ENCRYPT
```suggestion
    - name: settings.mssql.options.encrypt
      env: MSSQL_ENCRYPT
```

2023-05-20 03:13 UTC, matsonj commented
Thanks @edgarrmondragon! I missed those somehow.

2023-05-22 16:51 UTC, edgarrmondragon approved these changes
Thanks @matsonj! We'll have to port it to the Hub (cc @pnadolny13)

2023-05-22 16:51 UTC, merged